language: python
python:
    - 2.7.8
    - 3.3

install:
    - pip install pytest pytest-cov sqlalchemy
    - travis_retry python setup.py install

script:
    - py.test AssertDB/Tests/test_default_init.py

notifications:
  slack: rbirm:fjJKXGPbjyXSGAKKaOU6GWEh
